from __future__ import annotations

import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol

from ...core.ports import EventSink
from ...core.usage import (
    UsageLedger,
    UsageSummary,
    summarize_usage,
)


class _MemoryView(Protocol):
    @property
    def root(self) -> Path: ...

    @property
    def backlog(self) -> Any: ...

    @property
    def journal(self) -> Any: ...

    def render_prelude(self, *, objective: str = "") -> str: ...

def _local_day_start(now: float) -> float:
    local = time.localtime(now)
    return time.mktime((local.tm_year, local.tm_mon, local.tm_mday, 0, 0, 0, 0, 0, -1))


def global_daily_usage_summary(
    *,
    global_root: Path | None = None,
    now: float | None = None,
) -> UsageSummary:
    """Call-ledger usage across all projects since local midnight."""
    now = time.time() if now is None else float(now)
    day_start = _local_day_start(now)
    if global_root is None:
        from ...core.paths import global_root as resolve_global_root

        root = resolve_global_root()
    else:
        root = Path(global_root).expanduser()
    from ...core.paths import session_states_root

    projects_dir = session_states_root(root)
    try:
        project_dirs = sorted(p for p in projects_dir.iterdir() if p.is_dir())
    except OSError:
        return summarize_usage([])

    records = []
    for project_dir in project_dirs:
        try:
            records.extend(
                UsageLedger(project_dir, migrate_legacy=False).records(since=day_start)
            )
        except Exception:  # noqa: BLE001 — one corrupt project must not hide others
            continue
    return summarize_usage(records)


def global_daily_spend(*, global_root: Path | None = None, now: float | None = None) -> float:
    """Known call-ledger spend across all projects since local midnight."""
    return global_daily_usage_summary(
        global_root=global_root,
        now=now,
    ).known_cost_usd


@dataclass
class LifeBudget:
    """Host-global daily cost limit plus a non-monetary iteration guard."""

    global_daily_cap_usd: float = 0.0
    max_missions: int = 6

    def can_start(
        self,
        *,
        now: float | None = None,
        global_root: Path | None = None,
    ) -> tuple[bool, str]:
        """Cheap preflight; call admission rechecks settled global spend."""
        global_cap = float(self.global_daily_cap_usd or 0.0)
        if global_cap > 0:
            spent = global_daily_spend(global_root=global_root, now=now)
            if spent >= global_cap:
                return False, (
                    f"global daily budget exhausted "
                    f"(${spent:.2f} spent / ${global_cap:.2f})"
                )
        return True, ""

@dataclass
class LifeSupervisorConfig:
    """Knobs for one ``LifeSupervisor`` run."""

    budget: LifeBudget = field(default_factory=LifeBudget)
    poll_interval_seconds: float = 5.0
    # The real repository worktree for this project. When present, the
    # supervisor should run engineer / planner work there instead of in
    # the life metadata directory.
    project_worktree: Path | None = None
    # Highest-level kill switch — the supervisor checks this between
    # missions. The CLI sets it on SIGTERM/SIGINT.
    stop_event: threading.Event | None = None
    # Optional callable consulted at the start of every mission; should
    # return one pending operator nudge per call (or ``None`` when the
    # bus is empty). The supervisor splices each message into the
    # prelude_context so the engineer sees it as live operator
    # guidance. The default ``None`` disables the bus.
    user_inbox: Any = None  # Callable[[], str | None] | None
    # Manager-mediated resolver for one durable pending question. The callback
    # receives ``(blocked_item, operator_message)`` and returns the authoritative
    # answer result. Hosts wire the same resolver used by the web answer path.
    pending_question_resolver: Any = None
    # Runtime context injected into the prelude of every mission so
    # the agent knows its own backend, models, and budget constraints.
    # Set by the cockpit / daemon worker; empty string disables injection.
    runtime_context: str = ""
    # A/B switch shared by all four roles' direct project-layer Skill edits.
    role_skill_maintenance_enabled: bool = True
    # Default cycle count for tasks generated by the continuous planner.
    planner_task_iteration_max_cycles: int = 6
    # Subagent family failure circuit breaker (F6). A planner-generated task
    # is reworded from scratch every cycle, so the exact-text dedup below
    # (``_planner_task_signature``) cannot catch "the SAME underlying
    # experiment keeps failing" across differently-worded retries — and the
    # mission itself is often graded a success (the engineer DID resubmit +
    # monitor + document real work) even while the subagent job it launched
    # keeps erroring. ``_recent_subagent_family_failures`` reads the subagent
    # registry directly (``.argus_subagents/*.json``) and flags an experiment
    # family once it has failed this many times in a row, unresolved, within
    # the trailing window — independent of mission-level wording or grading.
    # See ``life/supervisor/_subagent_family_failures.py`` for the observed
    # pathology (SWE-bench full-canary retried ~20x/2 days before this fix).
    subagent_family_failure_streak_limit: int = 3
    subagent_family_failure_window_hours: float = 72.0
    # --- Continuous improvement mode -----------------------------------
    # When enabled, the supervisor does not exit when the backlog is
    # empty. Instead it invokes the planner to inspect the
    # project and generate the next batch of tasks. The supervisor
    # only stops when the planner declares the project done, or when
    # budget / stop_event fires.
    continuous: bool = False
    continuous_objective: str = ""
    # Explicit mission-type signals (replace the old keyword sniffing of the
    # objective text). ``paper_mission`` toggles the long-horizon paper guidance
    # the planner hands to bounded items; ``full_paper_gate`` requires the L2
    # reviewer's full-pipeline checklist to be certified before ``project_done``
    # is honoured (and drives the auto-stop once that gate passes). Both default
    # False: callers enable these only after the Manager has resolved
    # a vertical whose completion gate is explicitly ``full_paper``.
    paper_mission: bool = False
    full_paper_gate: bool = False
    # ``open_ended`` controls what happens when the planner certifies
    # ``project_done`` on a continuous mission: when True the supervisor does
    # NOT hard-stop — it logs a planner retry and keeps the mission alive so the
    # 7×24 lifetime agent keeps generating new work. Replaces the old keyword
    # sniffing of the objective text ("ongoing"/"perpetual"/"7×24"/…). Defaults
    # False at this low level (honour project_done); the daemon/cockpit entry paths
    # default it True unless ``--bounded`` is passed.
    open_ended: bool = False
    # Optional callback returning ``(enabled, objective)`` — the
    # supervisor calls it each iteration to hot-reload from disk or
    # elsewhere. When ``None``, the static ``continuous`` /
    # ``continuous_objective`` fields are used unchanged.
    continuous_config_provider: Any = None  # Callable[[], tuple[bool, str]] | None
    # Optional mission-boundary yield signal. A live operator Manager request
    # uses this to make ``run()`` return before the next tick/planner cycle so
    # the host can release its outer pipeline lock and commit configuration.
    manager_pipeline_yield_provider: Any = None  # Callable[[], bool] | None
    # Optional callback consulted immediately before each continuous
    # planner cycle. Return a non-empty stop reason to let the host
    # process defer planning and yield control, e.g. for daemon handoff.
    planner_cycle_gate: Any = None  # Callable[[], str] | None
    # Optional mission-boundary hook. The host may use this to perform
    # process-level actions that are only safe between missions (for example
    # blue/green handoff after the agent modifies its own daemon/runtime
    # architecture). Return a non-empty stop reason to end this drain pass.
    post_mission_hook: Any = None  # Callable[[dict[str, Any]], str] | None
    # Session-scoped directory for supervisor state sidecars.
    project_state_dir: Path | None = None
    # Session-scoped root for pipeline/checklist/domain artifacts. The command
    # working tree may be a git repo, but harness state must not leak across
    # sessions that share that repo.
    artifact_root: Path | None = None


class _MissionRunner(Protocol):
    """Structural type for the MissionExecutor we drive.

    We keep this loose so tests can substitute a fake without dragging
    ArgusBot in. Real callers pass an ``argus_skill.daemon.mission_executor.MissionExecutor``.
    """

    def execute(
        self,
        *,
        objective: str,
        original_objective: str = "",
        sink: EventSink,
        preload_injects: list[str] | None = None,
        prelude_context: str = "",
        scope: str = "",
        preplanned: bool = False,
    ) -> Any:  # MissionOutcome
        raise NotImplementedError
