// Generated by scripts/generate_event_payload_types.py. Do not edit.
import type { EventMsg } from './types.js';

export const EVENT_PAYLOAD_SCHEMA_VERSION = 1;

export interface AgentIoStartEvent extends EventMsg {
  type: "agent.io.start";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label": string;
  "backend"?: string;
  "model"?: string | null;
  "working_dir"?: string | null;
  "resume_thread_id"?: string | null;
}

export interface AgentIoStreamEvent extends EventMsg {
  type: "agent.io.stream";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label"?: string | null;
  "stream": "stdout" | "stderr";
  "line": string;
}

export interface AgentIoCompleteEvent extends EventMsg {
  type: "agent.io.complete";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label": string;
  "backend"?: string;
  "model"?: string | null;
  "exit_code"?: number | null;
  "thread_id"?: string | null;
  "fatal_error"?: string | null;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "cache_write_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number | null;
  "premium_requests_present"?: boolean;
  "total_nano_aiu"?: number | null;
}

export interface AgentIoErrorEvent extends EventMsg {
  type: "agent.io.error";
  payload_schema_version?: 1;
  "call_id": string;
  "run_label"?: string;
  "backend"?: string;
  "error": string;
}

export interface UsageRecordedEvent extends EventMsg {
  type: "usage.recorded";
  payload_schema_version?: 2;
  "call_id": string;
  "schema_version": 2;
  "project_id"?: string;
  "mission_id"?: string | null;
  "thread_id"?: string | null;
  "provider": string;
  "model"?: string;
  "run_label"?: string;
  "status": "completed" | "error" | "denied";
  "duration_ms"?: number;
  "usage": Record<string, unknown>;
  "pricing": Record<string, unknown>;
}

export interface ProviderRequestStartedEvent extends EventMsg {
  type: "provider.request.started";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "daily_calls"?: number;
  "daily_cap"?: number;
}

export interface ProviderRequestCompletedEvent extends EventMsg {
  type: "provider.request.completed";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "success"?: boolean;
  "error"?: string;
  "premium_requests"?: number;
}

export interface ProviderRequestDeniedEvent extends EventMsg {
  type: "provider.request.denied";
  payload_schema_version?: 1;
  "provider": string;
  "run_label": string;
  "call_id"?: string;
  "reason"?: string;
}

export interface BudgetReservationCreatedEvent extends EventMsg {
  type: "budget.reservation.created";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd": number;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface BudgetReservationDeniedEvent extends EventMsg {
  type: "budget.reservation.denied";
  payload_schema_version?: 1;
  "call_id": string;
  "reason": string;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface BudgetReservationSettledEvent extends EventMsg {
  type: "budget.reservation.settled";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd"?: number;
  "cost_usd"?: number | null;
  "overrun_usd"?: number | null;
  "pricing_status": string;
}

export interface BudgetReservationReleasedEvent extends EventMsg {
  type: "budget.reservation.released";
  payload_schema_version?: 1;
  "reservation_id": string;
  "call_id": string;
  "amount_usd"?: number;
  "reason"?: string;
}

export interface BudgetUnpricedBlockedEvent extends EventMsg {
  type: "budget.unpriced.blocked";
  payload_schema_version?: 1;
  "call_id": string;
  "reason": string;
  "provider"?: string;
  "model"?: string;
  "run_label"?: string;
}

export interface LifeMissionStartedEvent extends EventMsg {
  type: "life.mission.started";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "scope"?: string;
  "missions_started"?: number;
  "attempt"?: number;
  "usage_attempt_id"?: string;
}

export interface LifeMissionCompletedEvent extends EventMsg {
  type: "life.mission.completed";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "scope"?: string;
  "status": string;
  "outcome_class"?: "completed" | "incomplete" | "stalled" | "blocked" | "failed" | "ended";
  "outcome"?: { "execution_status": string; "review_status": string; "stage_certification": string; "interruption_kind": string; "resumable": boolean; };
  "success"?: boolean;
  "rounds"?: number;
  "elapsed_seconds"?: number;
  "cost_usd"?: number | null;
  "known_cost_usd"?: number;
  "pricing_status"?: string;
  "research_result"?: Record<string, unknown> | null;
  "repair_capability"?: Record<string, unknown> | null;
  "stop_kind"?: "budget_exhausted" | "provider_cooldown" | "provider_fence" | "daemon_shutdown" | "operator_pause" | "operator_abort" | "backend_unavailable" | "transient_error" | "permanent_error" | null;
  "recoverable"?: boolean;
}

export interface RoundStartEvent extends EventMsg {
  type: "round.start";
  payload_schema_version?: 1;
  "round_index": number;
  "round_max"?: number;
  "session_id"?: string | null;
}

export interface RoundMainCompletedEvent extends EventMsg {
  type: "round.main.completed";
  payload_schema_version?: 1;
  "round_index": number;
  "exit_code"?: number;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "stop_kind"?: "budget_exhausted" | "provider_cooldown" | "provider_fence" | "daemon_shutdown" | "operator_pause" | "operator_abort" | "backend_unavailable" | "transient_error" | "permanent_error" | null;
}

export interface RoundReviewStartedEvent extends EventMsg {
  type: "round.review.started";
  payload_schema_version?: 1;
  "round_index": number;
  "status"?: string;
}

export interface RoundReviewDeferredEvent extends EventMsg {
  type: "round.review.deferred";
  payload_schema_version?: 1;
  "round_index": number;
  "round_max"?: number;
  "next_step": string;
  "deferral_count"?: number;
  "deferral_limit"?: number;
}

export interface RoundReviewCompletedEvent extends EventMsg {
  type: "round.review.completed";
  payload_schema_version?: 1;
  "round_index"?: number;
  "status": "done" | "continue" | "blocked" | "replan_requested" | "error" | "research_incomplete" | "paused_no_breakthrough" | "exhausted_current_methods";
  "reason": string;
  "next_action"?: string;
  "operator_question"?: string;
  "review_source"?: string;
  "text"?: string;
  "review_skipped"?: boolean;
  "prompt_block_stats"?: Record<string, unknown>;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number;
  "backend_unavailable"?: boolean;
  "usage_scope"?: "delta";
  "stop_kind"?: "budget_exhausted" | "provider_cooldown" | "provider_fence" | "daemon_shutdown" | "operator_pause" | "operator_abort" | "backend_unavailable" | "transient_error" | "permanent_error" | null;
}

export interface RoundSecretRedactedEvent extends EventMsg {
  type: "round.secret_redacted";
  payload_schema_version?: 1;
  "round_index": number;
  "round_max"?: number;
  "redacted_paths": Array<string>;
  "replacement_count": number;
  "scanned_files"?: number;
  "scan_errors"?: Array<string>;
  "truncated"?: boolean;
  "operator_alert"?: boolean;
}

export interface LifePlannerStartEvent extends EventMsg {
  type: "life.planner.start";
  payload_schema_version?: 1;
  "manager_intent"?: Record<string, unknown>;
  "cycle"?: number;
}

export interface LifePlannerVerdictEvent extends EventMsg {
  type: "life.planner.verdict";
  payload_schema_version?: 1;
  "status": "planned" | "completed" | "research_incomplete" | "paused_budget" | "paused_no_breakthrough" | "exhausted_current_methods" | "provider_cooldown" | "infra_blocked" | "error";
  "success": boolean;
  "recoverable": boolean;
  "reason": string;
  "summary": string;
  "project_id": string;
  "mission_id": string;
  "research_target_level"?: string | null;
  "correctness_status"?: string | null;
  "novelty_status"?: string | null;
  "significance_status"?: string | null;
  "stop_kind"?: string | null;
  "completion_kind"?: string | null;
  "delivery_id"?: string;
  "tasks_added"?: number;
}

export interface LifePlannerErrorEvent extends EventMsg {
  type: "life.planner.error";
  payload_schema_version?: 1;
  "error": string;
  "reason"?: string;
}

export interface LifePlannerTaskAddedEvent extends EventMsg {
  type: "life.planner.task_added";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "objective"?: string;
  "deps"?: Array<string>;
  "priority"?: number;
  "impact_score"?: number;
  "impact_area"?: string;
  "branch_id"?: string;
  "parent_branch_id"?: string | null;
}

export interface LifePlannerTaskSkippedEvent extends EventMsg {
  type: "life.planner.task_skipped";
  payload_schema_version?: 1;
  "item_id"?: string;
  "title"?: string;
  "reason": string;
}

export interface LifeManagerIntentCompletedEvent extends EventMsg {
  type: "life.manager.intent.completed";
  payload_schema_version?: 1;
  "intent_id": string;
  "item_id": string;
  "objective": string;
  "vertical": string;
  "kind": string;
  "stages": Array<string>;
  "reason"?: string;
}

export interface LifeInboxDrainedEvent extends EventMsg {
  type: "life.inbox.drained";
  payload_schema_version?: 1;
  "count": number;
  "messages": Array<string>;
}

export interface LifeOperatorQuestionPendingEvent extends EventMsg {
  type: "life.operator_question.pending";
  payload_schema_version?: 1;
  "item_id": string;
  "title"?: string;
  "question": string;
  "agent_layer"?: string;
}

export interface LifeOperatorQuestionAnsweredEvent extends EventMsg {
  type: "life.operator_question.answered";
  payload_schema_version?: 1;
  "item_id": string;
  "continuation_item_id": string;
  "question": string;
  "manager_decision": string;
}

export interface EngineerProgressEvent extends EventMsg {
  type: "engineer.progress";
  payload_schema_version?: 1;
  "kind": string;
  "text"?: string;
  "actor"?: string;
  "agent_layer"?: string;
  "message_id"?: string;
  "replace"?: boolean;
  "round_index"?: number;
  "experiment_id"?: string;
  "branch_id"?: string;
}

export interface SkillCreatedEvent extends EventMsg {
  type: "skill.created";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "text"?: string;
}

export interface SkillUpdatedEvent extends EventMsg {
  type: "skill.updated";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "text"?: string;
}

export interface SkillArchivedEvent extends EventMsg {
  type: "skill.archived";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name"?: string;
  "version"?: number;
  "scope"?: string;
  "path"?: string;
  "reason"?: string;
  "text"?: string;
}

export interface SkillCostCompletedEvent extends EventMsg {
  type: "skill.cost.completed";
  payload_schema_version?: 1;
  "agent_layer"?: string;
  "matcher_model"?: string;
  "distiller_model"?: string;
  "matcher": Record<string, unknown>;
  "distiller": Record<string, unknown>;
  "input_tokens"?: number;
  "cached_input_tokens"?: number;
  "output_tokens"?: number;
  "reasoning_output_tokens"?: number;
  "premium_requests"?: number;
  "usage_scope": "delta" | "cumulative";
}

export interface SkillOutcomeEvent extends EventMsg {
  type: "skill.outcome";
  payload_schema_version?: 1;
  "skill_name"?: string;
  "skill_hit": boolean;
  "skill_distilled": boolean;
  "matcher_model"?: string;
  "distiller_model"?: string;
  "matcher_tokens"?: number;
  "distiller_tokens"?: number;
  "rounds": number;
  "status": string;
  "success": boolean;
}

export interface SkillScientistStartedEvent extends EventMsg {
  type: "skill.scientist.started";
  payload_schema_version?: 1;
  "text"?: string;
}

export interface SkillScientistCreatedEvent extends EventMsg {
  type: "skill.scientist.created";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "name": string;
  "version"?: number;
  "path"?: string;
  "text"?: string;
}

export interface SkillTidiedEvent extends EventMsg {
  type: "skill.tidied";
  payload_schema_version?: 1;
  "name": string;
  "placement": "global" | "vertical";
  "vertical"?: string;
  "path": string;
  "text": string;
}

export interface SkillCompactedEvent extends EventMsg {
  type: "skill.compacted";
  payload_schema_version?: 1;
  "source_skill": string;
  "target_skill": string;
  "text"?: string;
}

export interface SkillCompactErrorEvent extends EventMsg {
  type: "skill.compact.error";
  payload_schema_version?: 1;
  "error": string;
  "text"?: string;
}

export interface SkillOpErrorEvent extends EventMsg {
  type: "skill.op.error";
  payload_schema_version?: 1;
  "operation": string;
  "name"?: string;
  "error": string;
  "text"?: string;
}

export interface SkillOpRefusedEvent extends EventMsg {
  type: "skill.op.refused";
  payload_schema_version?: 1;
  "operation": string;
  "name"?: string;
  "reason": string;
  "text"?: string;
}

export interface SkillProposalRejectedEvent extends EventMsg {
  type: "skill.proposal.rejected";
  payload_schema_version?: 1;
  "operation": string;
  "reason": string;
  "text"?: string;
}

export interface SkillDistillRejectedEvent extends EventMsg {
  type: "skill.distill.rejected";
  payload_schema_version?: 1;
  "name"?: string;
  "reason": string;
  "text"?: string;
}

export interface SkillRevisedEvent extends EventMsg {
  type: "skill.revised";
  payload_schema_version?: 1;
  "skill_id"?: string;
  "skill": string;
  "version": number;
  "path"?: string;
  "previous_version_path": string;
  "text"?: string;
}

export interface SkillUseRecordedEvent extends EventMsg {
  type: "skill.use.recorded";
  payload_schema_version?: 1;
  "skill_id": string;
  "skill_name": string;
  "task_fingerprint": string;
  "success": boolean;
  "successful_uses"?: number;
  "failed_uses"?: number;
  "text"?: string;
}

export interface SkillHistoryCompressedEvent extends EventMsg {
  type: "skill.history.compressed";
  payload_schema_version?: 1;
  "count": number;
  "keep_hot": number;
  "paths"?: Array<string>;
  "truncated"?: boolean;
  "bytes_before"?: number;
  "bytes_after"?: number;
  "bytes_saved"?: number;
  "text"?: string;
}

export interface SkillEvolutionCompletedEvent extends EventMsg {
  type: "skill.evolution.completed";
  payload_schema_version?: 1;
  "ops_proposed": number;
  "created": number;
  "updated": number;
  "archived": number;
  "rejected": number;
  "compaction_clusters"?: number;
  "compacted"?: number;
  "history_compressed"?: number;
  "history_bytes_saved"?: number;
  "errors"?: number;
  "project_skill_dir"?: string;
  "global_skill_dir"?: string;
  "project_skill_count"?: number;
  "global_skill_count"?: number;
  "text"?: string;
}

export interface WikiInitializedEvent extends EventMsg {
  type: "wiki.initialized";
  payload_schema_version?: 1;
  "project": string;
  "path": string;
  "auto": boolean;
  "text"?: string;
}

export interface WikiInitializationFailedEvent extends EventMsg {
  type: "wiki.initialization.failed";
  payload_schema_version?: 1;
  "workdir": string;
  "error": string;
  "text"?: string;
}

export interface WikiHookOkEvent extends EventMsg {
  type: "wiki.hook.ok";
  payload_schema_version?: 1;
  "project": string;
  "path": string;
  "sources_written": number;
  "scratch_written": number;
  "text"?: string;
}

export interface WikiHookWarningEvent extends EventMsg {
  type: "wiki.hook.warning";
  payload_schema_version?: 1;
  "operation": string;
  "error": string;
  "text"?: string;
}

export interface WikiCompactedEvent extends EventMsg {
  type: "wiki.compacted";
  payload_schema_version?: 1;
  "card_type": string;
  "page_id": string;
  "target_id": string;
  "retired_path"?: string;
  "evidence_sources"?: Array<string>;
  "text"?: string;
}

export interface WikiCompactErrorEvent extends EventMsg {
  type: "wiki.compact.error";
  payload_schema_version?: 1;
  "card_type"?: string;
  "page_id"?: string;
  "error": string;
  "text"?: string;
}

export interface WikiCreatedEvent extends EventMsg {
  type: "wiki.created";
  payload_schema_version?: 1;
  "page_id": string;
  "card_type": string;
  "title"?: string;
  "status"?: string;
  "path": string;
  "text"?: string;
}

export interface WikiUpdatedEvent extends EventMsg {
  type: "wiki.updated";
  payload_schema_version?: 1;
  "page_id": string;
  "card_type": string;
  "title"?: string;
  "status"?: string;
  "path": string;
  "text"?: string;
}

export interface WikiRetiredEvent extends EventMsg {
  type: "wiki.retired";
  payload_schema_version?: 1;
  "page_id": string;
  "card_type": string;
  "reason"?: string;
  "text"?: string;
}

export interface WikiSourceCreatedEvent extends EventMsg {
  type: "wiki.source.created";
  payload_schema_version?: 1;
  "source_id": string;
  "path": string;
  "text"?: string;
}

export interface WikiSourceSkippedEvent extends EventMsg {
  type: "wiki.source.skipped";
  payload_schema_version?: 1;
  "source_id": string;
  "reason": string;
  "text"?: string;
}

export interface WikiPromotionPromotedEvent extends EventMsg {
  type: "wiki.promotion.promoted";
  payload_schema_version?: 1;
  "card_type": string;
  "page_id": string;
  "from_status": string;
  "to_status": string;
  "references"?: number;
  "successful_references"?: number;
  "failed_references"?: number;
  "text"?: string;
}

export interface WikiPromotionDemotedEvent extends EventMsg {
  type: "wiki.promotion.demoted";
  payload_schema_version?: 1;
  "card_type": string;
  "page_id": string;
  "from_status": string;
  "to_status": string;
  "references"?: number;
  "successful_references"?: number;
  "failed_references"?: number;
  "text"?: string;
}

export interface WikiRetiredCompressedEvent extends EventMsg {
  type: "wiki.retired.compressed";
  payload_schema_version?: 1;
  "count": number;
  "keep_hot": number;
  "paths"?: Array<string>;
  "truncated"?: boolean;
  "bytes_before"?: number;
  "bytes_after"?: number;
  "bytes_saved"?: number;
  "text"?: string;
}

export interface WikiEvolutionCompletedEvent extends EventMsg {
  type: "wiki.evolution.completed";
  payload_schema_version?: 1;
  "wiki_count": number;
  "ops_proposed"?: number;
  "sources"?: number;
  "scratch_pages"?: number;
  "created"?: number;
  "updated"?: number;
  "retired"?: number;
  "skipped"?: number;
  "rejected"?: number;
  "promoted"?: number;
  "demoted"?: number;
  "compaction_clusters"?: number;
  "compacted"?: number;
  "retired_compressed"?: number;
  "retired_bytes_saved"?: number;
  "errors"?: number;
  "paths"?: Array<string>;
  "text"?: string;
}

export interface ProjectCompletedEvent extends EventMsg {
  type: "project.completed";
  payload_schema_version?: 1;
  "vertical": string;
  "source": string;
  "required_gate": string;
  "evidence_refs": Array<string>;
  "from_state": string;
  "agent_layer"?: string;
}

export interface ProjectCompletionRefusedEvent extends EventMsg {
  type: "project.completion_refused";
  payload_schema_version?: 1;
  "vertical": string;
  "source": string;
  "required_gate": string;
  "reason": string;
  "agent_layer"?: string;
}

export interface ResearchAchievementCertifiedEvent extends EventMsg {
  type: "research.achievement.certified";
  payload_schema_version?: 1;
  "achievement_id": string;
  "title": string;
  "goal": string;
  "summary"?: string;
  "evidence"?: Array<string>;
  "reviewer_certified": true;
}

export interface DaemonCommandSubmittedEvent extends EventMsg {
  type: "daemon.command.submitted";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "revision": number;
  "expected_revision"?: number | null;
}

export interface DaemonCommandCompletedEvent extends EventMsg {
  type: "daemon.command.completed";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "status": "applied" | "failed";
  "revision": number;
  "error"?: string;
  "result"?: Record<string, unknown>;
}

export interface DaemonCommandRejectedEvent extends EventMsg {
  type: "daemon.command.rejected";
  payload_schema_version?: 1;
  "command_id": string;
  "operation": string;
  "status": "rejected";
  "revision": number;
  "error": string;
}

export interface EventPayloadByType {
  "agent.io.start": AgentIoStartEvent;
  "agent.io.stream": AgentIoStreamEvent;
  "agent.io.complete": AgentIoCompleteEvent;
  "agent.io.error": AgentIoErrorEvent;
  "usage.recorded": UsageRecordedEvent;
  "provider.request.started": ProviderRequestStartedEvent;
  "provider.request.completed": ProviderRequestCompletedEvent;
  "provider.request.denied": ProviderRequestDeniedEvent;
  "budget.reservation.created": BudgetReservationCreatedEvent;
  "budget.reservation.denied": BudgetReservationDeniedEvent;
  "budget.reservation.settled": BudgetReservationSettledEvent;
  "budget.reservation.released": BudgetReservationReleasedEvent;
  "budget.unpriced.blocked": BudgetUnpricedBlockedEvent;
  "life.mission.started": LifeMissionStartedEvent;
  "life.mission.completed": LifeMissionCompletedEvent;
  "round.start": RoundStartEvent;
  "round.main.completed": RoundMainCompletedEvent;
  "round.review.started": RoundReviewStartedEvent;
  "round.review.deferred": RoundReviewDeferredEvent;
  "round.review.completed": RoundReviewCompletedEvent;
  "round.secret_redacted": RoundSecretRedactedEvent;
  "life.planner.start": LifePlannerStartEvent;
  "life.planner.verdict": LifePlannerVerdictEvent;
  "life.planner.error": LifePlannerErrorEvent;
  "life.planner.task_added": LifePlannerTaskAddedEvent;
  "life.planner.task_skipped": LifePlannerTaskSkippedEvent;
  "life.manager.intent.completed": LifeManagerIntentCompletedEvent;
  "life.inbox.drained": LifeInboxDrainedEvent;
  "life.operator_question.pending": LifeOperatorQuestionPendingEvent;
  "life.operator_question.answered": LifeOperatorQuestionAnsweredEvent;
  "engineer.progress": EngineerProgressEvent;
  "skill.created": SkillCreatedEvent;
  "skill.updated": SkillUpdatedEvent;
  "skill.archived": SkillArchivedEvent;
  "skill.cost.completed": SkillCostCompletedEvent;
  "skill.outcome": SkillOutcomeEvent;
  "skill.scientist.started": SkillScientistStartedEvent;
  "skill.scientist.created": SkillScientistCreatedEvent;
  "skill.tidied": SkillTidiedEvent;
  "skill.compacted": SkillCompactedEvent;
  "skill.compact.error": SkillCompactErrorEvent;
  "skill.op.error": SkillOpErrorEvent;
  "skill.op.refused": SkillOpRefusedEvent;
  "skill.proposal.rejected": SkillProposalRejectedEvent;
  "skill.distill.rejected": SkillDistillRejectedEvent;
  "skill.revised": SkillRevisedEvent;
  "skill.use.recorded": SkillUseRecordedEvent;
  "skill.history.compressed": SkillHistoryCompressedEvent;
  "skill.evolution.completed": SkillEvolutionCompletedEvent;
  "wiki.initialized": WikiInitializedEvent;
  "wiki.initialization.failed": WikiInitializationFailedEvent;
  "wiki.hook.ok": WikiHookOkEvent;
  "wiki.hook.warning": WikiHookWarningEvent;
  "wiki.compacted": WikiCompactedEvent;
  "wiki.compact.error": WikiCompactErrorEvent;
  "wiki.created": WikiCreatedEvent;
  "wiki.updated": WikiUpdatedEvent;
  "wiki.retired": WikiRetiredEvent;
  "wiki.source.created": WikiSourceCreatedEvent;
  "wiki.source.skipped": WikiSourceSkippedEvent;
  "wiki.promotion.promoted": WikiPromotionPromotedEvent;
  "wiki.promotion.demoted": WikiPromotionDemotedEvent;
  "wiki.retired.compressed": WikiRetiredCompressedEvent;
  "wiki.evolution.completed": WikiEvolutionCompletedEvent;
  "project.completed": ProjectCompletedEvent;
  "project.completion_refused": ProjectCompletionRefusedEvent;
  "research.achievement.certified": ResearchAchievementCertifiedEvent;
  "daemon.command.submitted": DaemonCommandSubmittedEvent;
  "daemon.command.completed": DaemonCommandCompletedEvent;
  "daemon.command.rejected": DaemonCommandRejectedEvent;
}

export type TypedArgusEvent = EventPayloadByType[keyof EventPayloadByType];
