// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+d61866a41131d13c";
export const RELEASE_SOURCE_DIGEST = "d61866a41131d13ca08817f5768949ab94f9f7f04779bbeda23561523af154ed";
