// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.2+039554a35e23fc3f";
export const RELEASE_SOURCE_DIGEST = "039554a35e23fc3ffa2cc0e9962f4902f4702887699f894b91298102083fc897";
