// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.2+374dee8727ba0ed8";
export const RELEASE_SOURCE_DIGEST = "374dee8727ba0ed8a024132001772c4bb7715bba32b33dbfae43708e5b51b4bf";
