"""Subagent tool: submit/supervise/monitor background jobs.

This package was split out of a single 2.6k-line module. The public API
(every name importable as ``argus_skill.tools.subagent.X``) is re-exported
here so existing imports keep working unchanged.
"""
from __future__ import annotations

from ._cli import (
    _FAILED_STATES,
    _OK_STATES,
    cmd_clean,
    cmd_list,
    cmd_reply,
    cmd_status,
    cmd_submit,
    cmd_wait,
    main,
)
from ._cpu_admission import (
    CpuAdmissionError,
    apply_current_process_affinity,
    available_cpu_ids,
    cpu_admission_lock,
    leased_cpu_ids,
    select_cpu_ids,
)
from ._direct_run import (
    _KNOB_ALIASES,
    _RL_COLLAPSE_GUIDANCE_CACHE,
    _RL_COLLAPSE_SKILL_REL,
    _RL_TRAINING_HINTS,
    _flag,
    _is_full_scale_rl,
    _looks_like_rl_training,
    _parse_launch_flags,
    _rl_collapse_guidance,
    _run_contract_preflight,
    _run_direct,
    _strip_skill_frontmatter,
    _terminate_proc,
)
from ._discuss_run import (
    DISCUSSION_DEADLINE_S,
    DISCUSSION_FIRST_REPLY_TIMEOUT,
    DISCUSSION_POLL_INTERVAL,
    MAX_SUPERVISOR_TURNS,
    _run_discussion,
    _supervisor_discuss,
)
from ._discussion_log import (
    _DISCUSSION_MSG_CAP,
    _append_discussion,
    _discussion_path,
    _engineer_turn_count,
    _mirror_discussion_md,
    _read_discussion,
    _render_discussion,
    _reset_discussion,
)
from ._llm import _run_codex
from ._normalize import (
    _EMPTY_CONCERN_PREFIXES,
    _EMPTY_CONCERNS,
    _HEALTH_ALIASES,
    _VALID_DECISIONS,
    _VALID_HEALTH,
    _clean_concern,
    _coerce_bool,
    _norm_decision,
    _norm_health,
)
from ._registry import (
    _QUIET_LOGS_ENV,
    DISCUSSION_STALE_AFTER_S,
    EXPERIMENT_HISTORY_REL,
    REGISTRY_DIR,
    SUPERVISOR_INTERVAL_CAP,
    SUPERVISOR_MODEL,
    SUPERVISOR_THREAD_MAX_CHECKS,
    _append_experiment_history,
    _child_env,
    _effective_run_dir,
    _format_metric_line,
    _is_pid_alive,
    _lane_of,
    _list_tasks,
    _open_discussion_blockers,
    _persist_experiment_record,
    _progress_summary,
    _read_status_json,
    _read_summary_tsv,
    _read_task,
    _registry_path,
    _run_dir_from_command,
    _write_task,
)
from ._reporting import (
    _alert_engineer,
    _build_report,
    _queue_to_inbox,
    _reply_back_block,
    _supervisor_summarize_report,
)
from ._supervised_preflight import (
    _next_monitor_interval,
    _supervisor_preflight,
)
from ._supervised_run import (
    _run_supervised,
    _supervisor_check,
)
from ._text import (
    _codex_agent_messages,
    _codex_last_agent_message,
    _codex_thread_id,
    _find_codex,
    _strip_code_fence,
    _tail_file,
)

__all__ = [
    "_VALID_DECISIONS",
    "_VALID_HEALTH",
    "_HEALTH_ALIASES",
    "_norm_decision",
    "_norm_health",
    "_coerce_bool",
    "_EMPTY_CONCERNS",
    "_EMPTY_CONCERN_PREFIXES",
    "_clean_concern",
    "_find_codex",
    "_tail_file",
    "_codex_agent_messages",
    "_codex_last_agent_message",
    "_strip_code_fence",
    "_codex_thread_id",
    "REGISTRY_DIR",
    "SUPERVISOR_MODEL",
    "SUPERVISOR_INTERVAL_CAP",
    "DISCUSSION_POLL_INTERVAL",
    "DISCUSSION_FIRST_REPLY_TIMEOUT",
    "DISCUSSION_DEADLINE_S",
    "MAX_SUPERVISOR_TURNS",
    "DISCUSSION_STALE_AFTER_S",
    "SUPERVISOR_THREAD_MAX_CHECKS",
    "EXPERIMENT_HISTORY_REL",
    "_RL_COLLAPSE_SKILL_REL",
    "_RL_COLLAPSE_GUIDANCE_CACHE",
    "_strip_skill_frontmatter",
    "_rl_collapse_guidance",
    "_RL_TRAINING_HINTS",
    "_looks_like_rl_training",
    "_is_full_scale_rl",
    "_KNOB_ALIASES",
    "_flag",
    "_run_contract_preflight",
    "_parse_launch_flags",
    "_supervisor_preflight",
    "_next_monitor_interval",
    "_DISCUSSION_MSG_CAP",
    "_discussion_path",
    "_append_discussion",
    "_reset_discussion",
    "_read_discussion",
    "_engineer_turn_count",
    "_render_discussion",
    "_supervisor_summarize_report",
    "_reply_back_block",
    "_build_report",
    "_queue_to_inbox",
    "_alert_engineer",
    "_registry_path",
    "_write_task",
    "_read_task",
    "_list_tasks",
    "_is_pid_alive",
    "_run_direct",
    "_run_codex",
    "_terminate_proc",
    "_mirror_discussion_md",
    "_append_experiment_history",
    "_persist_experiment_record",
    "_lane_of",
    "_open_discussion_blockers",
    "_QUIET_LOGS_ENV",
    "_child_env",
    "_run_dir_from_command",
    "_effective_run_dir",
    "_format_metric_line",
    "_supervisor_check",
    "_supervisor_discuss",
    "_run_discussion",
    "_run_supervised",
    "_read_status_json",
    "_read_summary_tsv",
    "_progress_summary",
    "cmd_submit",
    "_OK_STATES",
    "_FAILED_STATES",
    "cmd_status",
    "cmd_list",
    "cmd_wait",
    "cmd_clean",
    "cmd_reply",
    "CpuAdmissionError",
    "apply_current_process_affinity",
    "available_cpu_ids",
    "cpu_admission_lock",
    "leased_cpu_ids",
    "select_cpu_ids",
    "main",
]
