"""Promote a proven project-local DATA domain into the argus SOURCE tree.

The hybrid domain lifecycle's second half: a data domain
(``research/DOMAINS/<name>.json`` + the Planner-authored
``research/CHECKLISTS.json``) that has proven out is rendered into a real
``argus_skill/verticals/<name>/`` Python package, so a good domain becomes a
version-controlled, shipped vertical. Source writes and optional commits use the
neutral :mod:`argus_skill.manager.source_writeback` boundary.

USER APPROVAL IS MANDATORY. Writing a domain back into the argus source is an
irreversible, outward-facing change, so :func:`promote_data_domain` writes ONLY
when called with ``approved=True``. The end-of-mission hook
(:func:`tidy_domains_after_mission`) NEVER writes on its own — in a headless run
it only SURFACES promotion proposals for the operator to approve; an interactive
front-end collects approval and then calls :func:`promote_data_domain` with
``approved=True``. The whole feature is additionally gated by
``ARGUS_SKILL_PROMOTE_DOMAINS`` (default OFF), and the git commit is gated by the
same ``ARGUS_SKILL_AUTOCOMMIT_SKILLS`` as skill writeback.
"""
from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import source_writeback

log = logging.getLogger(__name__)


def promotions_enabled() -> bool:
    """Whether the data-domain → source promotion flow is enabled at all.

    Default OFF: promotion writes to the operator's source tree, so it is opt-in
    via ``ARGUS_SKILL_PROMOTE_DOMAINS=1``. Even when enabled, each writeback still
    requires explicit per-domain approval (``promote_data_domain(approved=True)``).
    """
    return os.environ.get("ARGUS_SKILL_PROMOTE_DOMAINS", "").strip().lower() in {
        "1", "true", "yes", "on",
    }


@dataclass
class DomainPromotionProposal:
    """A proven, unpromoted data domain awaiting operator approval to write back."""

    name: str
    stages: list[str]
    checklist_stage_order: list[str] = field(default_factory=list)
    rendered_stages_py: str = ""
    reason: str = ""


def _verticals_root() -> Path:
    """The ``argus_skill/verticals`` source dir (inside the repo)."""
    return Path(__file__).resolve().parents[1] / "verticals"


def _vertical_package_path(name: str) -> Path:
    if not name or "/" in name or "\\" in name or name.startswith("."):
        raise ValueError(f"invalid vertical name: {name!r}")
    return _verticals_root() / name


def _domain_is_proven(project_root: Path) -> bool:
    """Cheap 'has this domain made real progress' heuristic.

    Proven when ``research/PIPELINE_STATE.json`` shows at least one completed
    stage (``stages.<s>.status == "done"``) or at least one advance in
    ``stage_history``. Fail-open to False so a missing/corrupt state file never
    triggers a promotion proposal.
    """
    try:
        payload = json.loads(
            (project_root / "research" / "PIPELINE_STATE.json").read_text(encoding="utf-8")
        )
    except Exception:  # noqa: BLE001 — no/!valid state → not proven
        return False
    if not isinstance(payload, dict):
        return False
    stages = payload.get("stages")
    if isinstance(stages, dict):
        for rec in stages.values():
            if isinstance(rec, dict) and str(rec.get("status") or "").lower() == "done":
                return True
    history = payload.get("stage_history")
    if isinstance(history, list):
        for h in history:
            if isinstance(h, dict) and str(h.get("direction") or "").lower() == "advance":
                return True
    return False


def _render_stages_py(name: str, project_root: Path) -> str:
    """Render the ``stages.py`` source for a promoted data domain.

    STAGE_ORDER / CHECKLIST_STAGE_ORDER come from the data domain; CHECKLIST_ITEMS
    are a SNAPSHOT of the Planner-authored ``research/CHECKLISTS.json`` (falling
    back to the data domain's own seed items per stage). Mirrors the attribute
    surface the ``verticals._base`` accessors read.
    """
    from ..skills.checklist_store import store_items_for_stage
    from ..verticals._data_domain import load_data_domain

    domain = load_data_domain(name, project_root)
    if domain is None:
        raise ValueError(f"data domain {name!r} not loadable")

    stage_order = list(domain.STAGE_ORDER)
    checklist_order = list(domain.CHECKLIST_STAGE_ORDER) or stage_order

    def _items_for(stage: str) -> list[Any]:
        effective = store_items_for_stage(project_root, stage)
        if effective is None:
            return list(domain.CHECKLIST_ITEMS.get(stage, ()))
        return list(effective)

    lines: list[str] = []
    lines.append(f'"""Auto-promoted data domain `{name}` — generated by domain_tidy.')
    lines.append("")
    lines.append("Promoted from a project-local data domain + its Planner-authored")
    lines.append("checklist snapshot. Edit here once promoted; the source package now")
    lines.append('wins over the (now-inert) project data domain on resolution."""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from ...skills.stage_machine import ChecklistItem")
    lines.append("")
    lines.append(f"STAGE_ORDER = {stage_order!r}")
    lines.append(f"CHECKLIST_STAGE_ORDER = {tuple(checklist_order)!r}")
    lines.append(f"completion_gate = {domain.completion_gate!r}")
    lines.append("")
    lines.append("CHECKLIST_ITEMS = {")
    for stage in checklist_order:
        items = _items_for(stage)
        if not items:
            lines.append(f"    {stage!r}: (),")
            continue
        lines.append(f"    {stage!r}: (")
        for it in items:
            lines.append(
                f"        ChecklistItem(id={it.id!r}, statement={it.statement!r}, "
                f"evidence_hint={getattr(it, 'evidence_hint', '')!r}),"
            )
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    banner = domain.role_banner("")
    lines.append("def role_banner(role: str) -> str:  # noqa: ARG001")
    lines.append(f"    return {banner!r}")
    lines.append("")
    return "\n".join(lines)


def propose_promotions(project_root: Path | str) -> list[DomainPromotionProposal]:
    """Return proposals for proven, unpromoted data domains (writes NOTHING).

    Used by the end-of-mission hook to surface what COULD be promoted, so an
    operator can approve. Fail-open to ``[]``."""
    if not promotions_enabled():
        return []
    root = Path(project_root)
    out: list[DomainPromotionProposal] = []
    try:
        from ..verticals._data_domain import list_data_domains, load_data_domain
    except Exception:  # noqa: BLE001
        return out
    if not _domain_is_proven(root):
        return out
    for name in list_data_domains(root):
        try:
            domain = load_data_domain(name, root)
            if domain is None:
                continue
            # Skip a domain whose Python package already exists (already promoted).
            if _vertical_package_path(name).exists():
                continue
            out.append(DomainPromotionProposal(
                name=name,
                stages=list(domain.STAGE_ORDER),
                checklist_stage_order=list(domain.CHECKLIST_STAGE_ORDER),
                rendered_stages_py=_render_stages_py(name, root),
                reason="proven (a stage completed) and not yet in source",
            ))
        except Exception:  # noqa: BLE001 — one bad domain never aborts the sweep
            log.debug("propose_promotions: skipped %r", name, exc_info=True)
    return out


def promote_data_domain(
    project_root: Path | str,
    name: str,
    *,
    approved: bool = False,
    on_event: Any = None,
) -> Path | None:
    """Write a data domain into ``argus_skill/verticals/<name>/`` and commit it.

    REQUIRES ``approved=True`` — promotion writes to the argus source tree (an
    irreversible, outward-facing change) and must be explicitly approved by the
    operator. With ``approved=False`` this is a no-op returning ``None`` (the
    caller must obtain approval first). Also requires ``ARGUS_SKILL_PROMOTE_DOMAINS``
    to be enabled. Fail-soft: a read-only tree / non-git / render error logs and
    returns ``None``. Returns the written ``stages.py`` path on success.
    """
    if not approved:
        log.info("promote_data_domain(%r): not approved — refusing to write to source", name)
        return None
    if not promotions_enabled():
        log.info("promote_data_domain(%r): ARGUS_SKILL_PROMOTE_DOMAINS disabled", name)
        return None
    root = Path(project_root)
    try:
        pkg = _vertical_package_path(name)
        if pkg.exists():
            log.info("promote_data_domain(%r): package already exists; skipping", name)
            return None
        stages_src = _render_stages_py(name, root)
        init_path = pkg / "__init__.py"
        stages_path = pkg / "stages.py"
        source_writeback.atomic_write(
            init_path, f'"""Promoted data domain `{name}`."""\n'
        )
        source_writeback.atomic_write(stages_path, stages_src)
    except Exception:  # noqa: BLE001 — promotion is best-effort
        log.warning("promote_data_domain(%r) failed to render/write", name, exc_info=True)
        return None

    # Mark the data domain promoted (the Python package now wins on resolution).
    try:
        from ..verticals._data_domain import mark_promoted

        mark_promoted(root, name)
    except Exception:  # noqa: BLE001
        log.debug("mark_promoted(%r) failed", name, exc_info=True)

    _emit(on_event, f"promoted data domain `{name}` → verticals/{name}/ (operator-approved)")
    msg = f"feat(verticals): promote data domain `{name}` to source [manager, operator-approved]"
    if not source_writeback.commit_to_source([init_path, stages_path], msg):
        log.info("promote_data_domain(%r): wrote package but did not commit (left in tree)", name)
    return stages_path


def tidy_domains_after_mission(
    project_root: Path | str,
    *,
    approve: Any = None,
    on_event: Any = None,
) -> list[str]:
    """End-of-mission domain promotion sweep — NEVER writes without approval.

    Surfaces proven, unpromoted data domains. ``approve`` is an optional callback
    ``approve(proposal) -> bool`` supplied by an INTERACTIVE front-end; only a
    proposal it approves is written via :func:`promote_data_domain`. With
    ``approve=None`` (the headless default) nothing is written — each pending
    promotion is merely emitted/logged so the operator can approve it later.
    Returns the list of domain names actually promoted (empty in headless runs).
    """
    promoted: list[str] = []
    try:
        proposals = propose_promotions(project_root)
    except Exception:  # noqa: BLE001 — must never block mission completion
        log.debug("tidy_domains_after_mission: propose failed", exc_info=True)
        return promoted
    for proposal in proposals:
        if not callable(approve):
            _emit(
                on_event,
                f"data domain `{proposal.name}` is proven and could be promoted to "
                f"source — operator approval required (no interactive turn here)",
            )
            continue
        try:
            if approve(proposal):
                path = promote_data_domain(
                    project_root, proposal.name, approved=True, on_event=on_event
                )
                if path is not None:
                    promoted.append(proposal.name)
        except Exception:  # noqa: BLE001 — one bad promotion never aborts the sweep
            log.debug("tidy_domains_after_mission: promote %r failed", proposal.name, exc_info=True)
    return promoted


def _emit(on_event: Any, text: str) -> None:
    if callable(on_event):
        try:
            on_event({"type": "domain.promotion", "text": text})
        except Exception:  # noqa: BLE001 — event sink must never break tidy
            pass


__all__ = [
    "DomainPromotionProposal",
    "promotions_enabled",
    "propose_promotions",
    "promote_data_domain",
    "tidy_domains_after_mission",
]
