#!/usr/bin/env python3
"""Generate the shared TypeScript resource-ledger status model."""

from __future__ import annotations

import argparse
import json
import pprint
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator

ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = (
    ROOT
    / "argus_skill"
    / "tools"
    / "resource_ledger"
    / "resource_ledger_status.schema.json"
)
OUTPUT_PATH = ROOT / "frontend" / "core" / "src" / "resourceStatus.generated.ts"
PYTHON_OUTPUT_PATH = (
    ROOT
    / "argus_skill"
    / "tools"
    / "resource_ledger"
    / "status_schema_generated.py"
)


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)
    return str(value)


def _ts_type(schema: dict[str, Any]) -> str:
    reference = schema.get("$ref")
    if isinstance(reference, str):
        prefix = "#/$defs/"
        if not reference.startswith(prefix):
            raise ValueError(f"unsupported schema reference: {reference}")
        return reference.removeprefix(prefix)
    variants = schema.get("anyOf")
    if isinstance(variants, list):
        return " | ".join(_ts_type(variant) for variant in variants)
    if "const" in schema:
        return _literal(schema["const"])
    enum = schema.get("enum")
    if isinstance(enum, list):
        return " | ".join(_literal(value) for value in enum)
    raw_type = schema.get("type")
    if raw_type == "string":
        return "string"
    if raw_type in {"integer", "number"}:
        return "number"
    if raw_type == "boolean":
        return "boolean"
    if raw_type == "null":
        return "null"
    if raw_type == "array":
        items = schema.get("items")
        if not isinstance(items, dict):
            raise ValueError("array schema is missing items")
        return f"ReadonlyArray<{_ts_type(items)}>"
    raise ValueError(f"unsupported schema type: {raw_type!r}")


def _interface(name: str, schema: dict[str, Any]) -> list[str]:
    properties = schema.get("properties")
    if schema.get("type") != "object" or not isinstance(properties, dict):
        raise ValueError(f"{name} must be an object schema")
    required = set(schema.get("required") or [])
    lines = [f"export interface {name} {{"]
    for field, field_schema in properties.items():
        optional = "" if field in required else "?"
        lines.append(
            f"  readonly {json.dumps(field)}{optional}: {_ts_type(field_schema)};"
        )
    lines.extend(["}", ""])
    return lines


def render() -> str:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    Draft202012Validator.check_schema(schema)
    lines = [
        "// Generated by argus_skill.release_tools.generate_resource_status. Do not edit.",
        "",
    ]
    for name, definition in schema.get("$defs", {}).items():
        lines.extend(_interface(name, definition))
    lines.extend(_interface(str(schema["title"]), schema))
    return "\n".join(lines)


def render_python() -> str:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    Draft202012Validator.check_schema(schema)
    literal = pprint.pformat(schema, width=100, sort_dicts=False)
    return f'''# Generated by argus_skill.release_tools.generate_resource_status. Do not edit.
from __future__ import annotations

from typing import Any

from jsonschema import Draft202012Validator

RESOURCE_STATUS_SCHEMA: dict[str, Any] = {literal}
_VALIDATOR = Draft202012Validator(RESOURCE_STATUS_SCHEMA)


def validate_resource_status(payload: dict[str, Any]) -> dict[str, Any]:
    _VALIDATOR.validate(payload)
    return payload
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    artifacts = {
        OUTPUT_PATH: render(),
        PYTHON_OUTPUT_PATH: render_python(),
    }
    if args.check:
        stale = [
            path
            for path, expected in artifacts.items()
            if not path.exists() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            raise SystemExit(
                "generated resource status contracts are stale; run "
                "python -m argus_skill.release_tools.generate_resource_status"
            )
        return 0
    for path, rendered in artifacts.items():
        # Git ships LF bytes on every platform. Avoid Windows newline
        # translation, which would make the release digest differ after clone.
        path.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
