#!/usr/bin/env python3
"""Generate the backend/frontend release identity from shipped source."""

from __future__ import annotations

import argparse
import json
import os
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from argus_skill.release import MANIFEST_SCHEMA_VERSION, compute_source_digest  # noqa: E402

MANIFEST_PATH = ROOT / "argus_skill" / "release_manifest.json"
TS_PATH = ROOT / "frontend" / "core" / "src" / "release.generated.ts"


def render() -> tuple[str, str]:
    project = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    package_version = os.environ.get("ARGUS_RELEASE_VERSION", "").strip() or str(
        project["project"]["version"]
    )
    source_digest = compute_source_digest(ROOT)
    release_id = f"{package_version}+{source_digest[:16]}"
    manifest = json.dumps(
        {
            "schema_version": MANIFEST_SCHEMA_VERSION,
            "package_version": package_version,
            "source_digest": source_digest,
            "release_id": release_id,
        },
        indent=2,
        sort_keys=True,
    ) + "\n"
    generated = (
        "// Generated by scripts/generate_release_manifest.py. Do not edit.\n"
        f"export const RELEASE_ID = {json.dumps(release_id)};\n"
        f"export const RELEASE_SOURCE_DIGEST = {json.dumps(source_digest)};\n"
    )
    return manifest, generated


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument(
        "--prepare-build",
        action="store_true",
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args(argv)
    if not args.check and not args.prepare_build:
        parser.error(
            "release identity cannot be updated without rebuilding the shipped "
            "frontends; run scripts/build_release.py"
        )
    manifest, generated = render()
    if args.check:
        current_manifest = (
            MANIFEST_PATH.read_text(encoding="utf-8") if MANIFEST_PATH.exists() else ""
        )
        current_ts = TS_PATH.read_text(encoding="utf-8") if TS_PATH.exists() else ""
        if current_manifest != manifest or current_ts != generated:
            raise SystemExit(
                "release manifest is stale; run scripts/build_release.py"
            )
        return 0
    MANIFEST_PATH.write_text(manifest, encoding="utf-8")
    TS_PATH.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
