#!/usr/bin/env python3
"""Generate frontend event payload interfaces from the canonical JSON schema."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "argus_skill" / "core" / "event_payload_schemas.json"
OUTPUT_PATH = ROOT / "frontend" / "core" / "src" / "eventPayloads.generated.ts"


def _interface_name(event_type: str) -> str:
    parts = re.split(r"[._-]+", event_type)
    return "".join(part[:1].upper() + part[1:] for part in parts) + "Event"


def _literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value)
    return str(value)


def _ts_type(schema: dict[str, Any]) -> str:
    if "const" in schema:
        return _literal(schema["const"])
    if isinstance(schema.get("enum"), list):
        return " | ".join(_literal(value) for value in schema["enum"])
    raw_type = schema.get("type")
    if isinstance(raw_type, list):
        return " | ".join(
            _ts_type({**schema, "type": item}) for item in raw_type
        )
    if raw_type == "string":
        return "string"
    if raw_type in {"integer", "number"}:
        return "number"
    if raw_type == "boolean":
        return "boolean"
    if raw_type == "null":
        return "null"
    if raw_type == "array":
        item_type = _ts_type(schema.get("items") or {})
        return f"Array<{item_type}>"
    if raw_type == "object":
        properties = schema.get("properties")
        if isinstance(properties, dict) and properties:
            required = set(schema.get("required") or [])
            fields = [
                f"{json.dumps(field)}{'' if field in required else '?'}: "
                f"{_ts_type(field_schema)};"
                for field, field_schema in properties.items()
            ]
            return "{ " + " ".join(fields) + " }"
        return "Record<string, unknown>"
    return "unknown"


def render() -> str:
    payload = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    events = payload["events"]
    lines = [
        "// Generated by scripts/generate_event_payload_types.py. Do not edit.",
        "import type { EventMsg } from './types.js';",
        "",
        f"export const EVENT_PAYLOAD_SCHEMA_VERSION = {int(payload['schema_version'])};",
        "",
    ]
    names: dict[str, str] = {}
    for event_type, schema in events.items():
        name = _interface_name(event_type)
        names[event_type] = name
        required = set(schema.get("required") or [])
        lines.extend([
            f"export interface {name} extends EventMsg {{",
            f"  type: {json.dumps(event_type)};",
            f"  payload_schema_version?: {int(schema.get('version') or 1)};",
        ])
        for field, field_schema in (schema.get("properties") or {}).items():
            optional = "" if field in required else "?"
            lines.append(
                f"  {json.dumps(field)}{optional}: {_ts_type(field_schema)};"
            )
        lines.extend(["}", ""])
    lines.append("export interface EventPayloadByType {")
    for event_type, name in names.items():
        lines.append(f"  {json.dumps(event_type)}: {name};")
    lines.extend([
        "}",
        "",
        "export type TypedArgusEvent = EventPayloadByType[keyof EventPayloadByType];",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        try:
            current = OUTPUT_PATH.read_text(encoding="utf-8")
        except OSError:
            current = ""
        if current != rendered:
            raise SystemExit(
                "generated event payload types are stale; run "
                "scripts/generate_event_payload_types.py"
            )
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
