"""Backtest adapter scaffold for the quant-factor domain.

The user's real backtest engine and data are assumed to exist but are *external*
to Argus. This module defines the thin contract Argus needs so the agent's
run-stage can drive *some* engine and have every trial captured in the search
ledger — without Argus owning a backtester.

Wire a real engine in by implementing :class:`BacktestEngine` (a ``Protocol``;
no subclassing required) and passing it to :func:`run_backtest`. The wrapper's
only job is **provenance**: it runs the engine and appends the result — success
or failure — to the :class:`~.search_ledger.SearchLedger` at the execution
boundary, so the search breadth is recorded by construction rather than
back-filled by the agent.

This is evidence capture, not a review gate: nothing here decides whether a
factor is good. The L2 reviewer reads the ledger and the report and rules.
"""
from __future__ import annotations

import hashlib
import json
import math
import time
import traceback
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable

from .search_ledger import LedgerRow, SearchLedger


@dataclass(frozen=True)
class BacktestSpec:
    """A single trial to run.

    Carries both *what* to test and the reproducibility context an auditor needs
    to re-run it. ``run_id`` is generated by the caller *before* execution so a
    crashed run still leaves a ledger row referencing it.
    """

    run_id: str
    factor_ids: Sequence[str]
    # "single" | "equal_weight" | "optimized" | ... — how factors are combined.
    weighting: str = "single"
    # Optimization inputs / combination weights, screen params, etc.
    params: Mapping[str, Any] = field(default_factory=dict)
    # Evaluation window label, e.g. "train", "validation", "test", or a
    # walk-forward window id. Drives the oos/is interpretation downstream.
    window: str = ""
    is_out_of_sample: bool = False
    # Reproducibility context (rubber-duck: metrics without this aren't auditable).
    universe: str = ""
    data_snapshot: str = ""
    seed: int | None = None


@dataclass(frozen=True)
class BacktestResult:
    """The outcome of one trial.

    ``metrics`` holds the numbers the analysis stage reads (IC, RankIC, ICIR,
    long-short return, turnover, cost-adjusted return, ...). ``status`` is
    ``"ok"`` on success or ``"error"`` on failure; ``warnings`` surfaces
    partial-failure / data-coverage caveats. ``engine`` identifies the engine
    build so a result can be reproduced.
    """

    run_id: str
    status: str = "ok"
    metrics: Mapping[str, float] = field(default_factory=dict)
    engine: str = ""
    config_hash: str = ""
    warnings: Sequence[str] = field(default_factory=tuple)
    error: str = ""
    metadata: Mapping[str, Any] = field(default_factory=dict)


@runtime_checkable
class BacktestEngine(Protocol):
    """The contract a real backtest engine must satisfy.

    A ``Protocol`` so any object with a matching ``run`` works — no Argus base
    class to inherit. ``name`` identifies the engine build for provenance.
    """

    name: str

    def run(self, spec: BacktestSpec) -> BacktestResult:
        ...


def _canonical_config(value: object) -> object:
    scalar_item = getattr(value, "item", None)
    if (
        type(value).__module__.startswith("numpy")
        and getattr(value, "ndim", None) == 0
        and callable(scalar_item)
    ):
        unpacked = scalar_item()
        if type(unpacked).__module__.startswith("numpy"):
            text = str(value)
            if text.strip().lower() in {
                "nan",
                "+nan",
                "-nan",
                "inf",
                "+inf",
                "-inf",
                "infinity",
                "+infinity",
                "-infinity",
            }:
                raise ValueError("configuration floats must be finite")
            return {
                "__numpy_scalar__": {
                    "dtype": str(getattr(value, "dtype", type(value).__name__)),
                    "value": text,
                }
            }
        return _canonical_config(unpacked)
    if value is None or isinstance(value, (bool, int, str)):
        return value
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError("configuration floats must be finite")
        return {"__float__": value.hex()}
    if isinstance(value, Mapping):
        if not all(isinstance(key, str) for key in value):
            raise TypeError("configuration mapping keys must be strings")
        return {
            "__mapping__": [
                [key, _canonical_config(value[key])]
                for key in sorted(value)
            ]
        }
    if isinstance(value, list):
        return {"__list__": [_canonical_config(item) for item in value]}
    if isinstance(value, tuple):
        return {"__tuple__": [_canonical_config(item) for item in value]}
    if isinstance(value, (set, frozenset)):
        items = [_canonical_config(item) for item in value]
        items.sort(
            key=lambda item: json.dumps(
                item,
                sort_keys=True,
                separators=(",", ":"),
            )
        )
        return {"__set__": items}
    raise TypeError(
        f"unsupported configuration value {type(value).__name__}; "
        "use JSON-like values, tuples, or sets"
    )


def config_fingerprint(
    *,
    engine_name: str,
    spec: BacktestSpec,
    engine_config: Mapping[str, Any] | None = None,
) -> str:
    """Return a deterministic fingerprint of every result-affecting setting."""
    canonical = json.dumps(
        _canonical_config(
            {
                "engine": engine_name,
                "engine_config": dict(engine_config or {}),
                "spec": {
                    "factor_ids": list(spec.factor_ids),
                    "weighting": spec.weighting,
                    "params": dict(spec.params),
                    "window": spec.window,
                    "is_out_of_sample": spec.is_out_of_sample,
                    "universe": spec.universe,
                    "data_snapshot": spec.data_snapshot,
                    "seed": spec.seed,
                },
            },
        ),
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


def _result_payload(spec: BacktestSpec, result: BacktestResult) -> dict[str, Any]:
    """Flatten a spec+result into a ledger row payload (audit-complete)."""
    payload = {
        "run_id": spec.run_id,
        "factor_ids": list(spec.factor_ids),
        "weighting": spec.weighting,
        "params": dict(spec.params),
        "window": spec.window,
        "is_out_of_sample": spec.is_out_of_sample,
        "universe": spec.universe,
        "data_snapshot": spec.data_snapshot,
        "seed": spec.seed,
        "status": result.status,
        "metrics": dict(result.metrics),
        "engine": result.engine,
        "config_hash": result.config_hash,
        "warnings": list(result.warnings),
        "error": result.error,
    }
    metadata = dict(result.metadata)
    payload["metadata"] = metadata
    for key in (
        "candidate_id",
        "decision",
        "cost_model_id",
        "net_of_cost",
        "buy_cost_bps",
        "sell_cost_bps",
        "minimum_trade_cost_cny",
        "slippage_bps_per_side",
        "limit_up_down_nontradable",
        "suspended_or_missing_bar_nontradable",
        "next_bar_execution_required",
    ):
        if key in metadata:
            payload[key] = metadata[key]
    return payload


def run_backtest(
    engine: BacktestEngine, spec: BacktestSpec, ledger: SearchLedger
) -> tuple[BacktestResult, LedgerRow]:
    """Run one trial and record it in the ledger at the execution boundary.

    Returns the engine's result and the ledger row written for it. A raised
    exception from the engine is caught, converted to an ``"error"`` result, and
    *still logged* — so a failed trial cannot silently vanish from the search
    breadth. The exception is not re-raised; callers inspect ``result.status``.
    """
    started = time.time()
    try:
        result = engine.run(spec)
    except Exception as exc:  # noqa: BLE001 - failures must be recorded, not lost
        result = BacktestResult(
            run_id=spec.run_id,
            status="error",
            engine=getattr(engine, "name", ""),
            error=f"{type(exc).__name__}: {exc}",
            warnings=(traceback.format_exc().strip(),),  # full traceback — reviewer audits the whole stack, not one line
            metadata={
                "candidate_id": spec.params.get("base_factor_id") or spec.run_id,
                "decision": {
                    "value": "error_recorded",
                    "rationale": "Engine raised; failed trial recorded for breadth accounting.",
                },
            },
        )
    payload = _result_payload(spec, result)
    payload["elapsed_s"] = round(time.time() - started, 6)
    row = ledger.append(payload)
    return result, row
